In [40]:
# Write a Python program to convert an array to an ordinary ilist with the same items.
# we can use the np.tolist() function
from array import *

feyi = array('i', [1,2,3,4,5,6,7,10])
print("Original array: "+str(np))
feyi = feyi.tolist()
print("Convert an array to an ordinary list with the same items: ")
print(feyi)

Original array: <module 'numpy' from 'C:\\Users\\HP\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>
Convert an array to an ordinary list with the same items: 
[1, 2, 3, 4, 5, 6, 7, 10]


In [41]:
# Write a NumPy program to compute the sum of the diagonal elements of a given array.
# Hint: Two methods to solve this problem: 1. manually(without direct function). 2. using the trace function

import numpy as np
feyi = np.arange(6).reshape(2,3)
print("Original matrix:")
print(feyi)
result = np.trace(feyi)
print("Condition number of the said matrix:")
print(result)

Original matrix:
[[0 1 2]
 [3 4 5]]
Condition number of the said matrix:
4


In [78]:
# Given an array of your choice, get all the values higher than X :
# if a = [[1,2],[3,5]] and x = 2 :  then 3 and 5 are higher than 2. 
import numpy as np 

a = np.array([[1,2],[3,5]])
x = 2
print("Original array: ")
print(x)
print("Value bigger than x =", [x>2] ,[3,5>2])

Original array: 
2
Value bigger than x = [False] [3, True]


In [97]:
# Given two arrays, A & B have the same shape. 
# The task is to apply addition by hand: C is the new array. 

a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
sum = a + b
c = sum
print("\cNew Array:\c")
print(c)

\cNew Array:\c
[2 4 6 8]


In [82]:
# Write a NumPy program to subtract the mean of each row of a given matrix.

print("Original matrix:\n")
a = np.random.rand(2,4)
print(a)
print("\nSubtract the mean of each row of the said matrix:\n")
b = a - a.mean(axis=1, keepdims=True)
print(b)

Original matrix:

[[0.61825589 0.94388861 0.48728697 0.84542796]
 [0.04575845 0.05402025 0.74989203 0.61140631]]

Subtract the mean of each row of the said matrix:

[[-0.10545897  0.22017375 -0.23642788  0.1217131 ]
 [-0.3195108  -0.31124901  0.38462277  0.24613705]]
